BEGIN
    -- Usuniêcie tabel zagnie¿d¿onych najpierw
    EXECUTE IMMEDIATE 'DROP TABLE OfertyWakacyjne_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE OcenyHoteli_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Promocje_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Rezerwacje_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Uzytkownicy_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Hotele_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Atrakcje_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Oceny_tab CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Adresy_tab CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
            RAISE;
        END IF;
        -- Jeœli tabela nie istnieje, kontynuuj
END;